version: "3"
services:
  node: 
    image: "epfldojo/gitlabstatisticsprometheusexporter:latest"
    container_name: "GitlabStatsExporter"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
      - PRIVATE_TOKEN=${PRIVATE_TOKEN}
      - GITLAB_URL=${GITLAB_URL:-https://gitlab.epfl.ch}
      - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
