version: "3"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PRIVATE_TOKEN=${PRIVATE_TOKEN}
      - GITLAB_URL=${GITLAB_URL:-'https://gitlab.epfl.ch'}
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"