version: "3"
services:
  node: 
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PRIVATE_TOKEN=${PRIVATE_TOKEN}
      - GITLAB_URL=${GITLAB_URL:-https://gitlab.epfl.ch}
      - PORT=${PORT:-3000}
    volumes:
      - ./:/home/node/app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: "npm start"